### PR TITLE
Running ansible after created the droplet

### PR DESCRIPTION
**Pull request by nodauf**
Small modification to start the ansible playbook once the droplet is created with terraform.

### CODE REVIEW

**Comment by aaaguirrep** [comment]
Hi @nodauf, thanks for your collaboration, I have tested the changes and I have identified the next issues to check:

- When the server is created it is not able to connect by 22 port immediately, there is a delay (1 or 2 minutes) to run ansible. Can you setup a sleep before launch ansible?
```
TASK [Gathering Facts] *********************************************************
fatal: [X.X.X.X]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host X.X.X.X port 22: Connection refused", "unreachable": true}
```

- The change applies when you create a server but if you create two or more servers it should iterate all public ip address to build host.cfg file.

Can you check both issues?

Thanks in advance.

Regards,
Arsenio

**Comment by nodauf** [comment]
Thank you for the feed back. I will correct the issue

**Comment by nodauf** [comment]
I have add the sleep command (60 secondes) and I now use the tuples of all external IP which I join to create the inventory for ansible

**Review by aaaguirrep — APPROVED** [review]
Excellent.

**Pull request merged**
